version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ProcessTaskDev
      POSTGRES_USER: ProcessTaskDev
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8100:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./front/build:/var/www/html
    depends_on:
      - web

volumes:
  postgres_data:
